### ISSUE TITLE
Lying Read.me

### ISSUE THREAD

**Issue by Damianu** [CaptainPRICE/Wire-Data-New#30]
It says that it contains starfall scripts, I wanted to steal them and take credit, but I cant find them. Can you help me?

**Comment by CaptainPRICE** [comment]
> It says that it contains starfall scripts, I wanted to steal them and take credit, but I cant find them.

No, it doesn't say that. It says that I use this repository for "sharing" stuff with public.
Guess what? I have not shared any Starfall script with public, yet.

All of the code in this repository is open-source with copyright, and is licensed under the MIT license.

> Can you help me?
No, I can't help you.

* Closing this issue to avoid wasting of my time, if you have any other questions, please open a new issue.
